In [1]:
import numpy as np # Don't forget to import numpy

np.random.seed(123)  # We are generating random number here, so it will be different every time.
                        # Setting a seed = 123 help us generate the exact same numbers
                         # next time when we call 123 for reproducibility purposes.
                            # You can use any number as a seed.
m1 = np.random.randint(0, 100, size = 10) # Create a array of 10 random integers in the interval [0, 100)
m2 = np.random.randint(10, size=(3, 4)) # Create a 3 x 4 array of in the interval [0, 10)
print("The one-dimensional array looks like this:\n", m1)
print("The two-dimensional array looks like this:\n", m2)

The one-dimensional array looks like this:
 [66 92 98 17 83 57 86 97 96 47]
The two-dimensional array looks like this:
 [[9 0 0 9]
 [3 4 0 0]
 [4 1 7 3]]


In [2]:
m1[0]

66

In [3]:
# You can count from the end
m1[-2]

96

In [4]:
# Same rules apply for multi-dimensional array
m2[0, -1] # First row, last column

9

In [5]:
m1[1:7:2] # accessing the second, forth, and sixth element

array([92, 17, 57])

In [6]:
m1[:5] # accessing the first five elements


array([66, 92, 98, 17, 83])

In [7]:
m1[5:] # accessing elements after the sixth element

array([57, 86, 97, 96, 47])

In [8]:
m1[::2] # every other elements

array([66, 98, 83, 86, 96])

In [9]:
m1[::-1] # all elements, reversed

array([47, 96, 97, 86, 57, 83, 17, 98, 92, 66])

In [10]:
m2[:2, :3] # first two rows, first three columns

array([[9, 0, 0],
       [3, 4, 0]])

In [11]:
m2[:, 0] # first column

array([9, 3, 4])

In [12]:
m2[0, :]  # first row
# This could be written in a compact format
m2[0]

array([9, 0, 0, 9])

In [13]:
m2[m2 > 1] # you can build masking to an array
           # this accesses all the elements greater than 1

array([9, 9, 3, 4, 4, 7, 3])

In [14]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [15]:
np.vstack([grid, grid+1]) # grid + 1 = every element in grid increments 1

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [16]:
ICEdata = pd.read_csv("ICE1_Data.csv")

ICEdata

NameError: name 'pd' is not defined

In [17]:
m2

array([[9, 0, 0, 9],
       [3, 4, 0, 0],
       [4, 1, 7, 3]])